### ISSUE TITLE
BeatSaber crashes on close after installing only BSIPA

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [nike4613/BeatSaber-IPA-Reloaded#26] opened 2019-11-09 03:09 UTC
Log makes it seem like I have closed the game quickly.  But I assure you that isn't the issue.  It seems to be hanging for a while at the point saying "[DEBUG @ 21:43:38 | IPA/Updater] To Download "

To clarify, I haven't done anything to the base game, but install BSIPA.  No Custom Songs or anything.  I"m using the latest ModAssistant 1.0.25 to install and my Steam install has no non-default config.

I'm unsure of what it is exactly trying to do here,  but if the dev can assist me in understanding how this normally works, I can try to figure out what might be going on.  

Any chance to run a debug version or enable debug logging?

[2019.11.08.21.43.34.log](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/files/3826872/2019.11.08.21.43.34.log)

**Comment by nike4613** [comment] 2019-11-09 22:22
That is a known bug, however is has been relatively low priority since it doesn't seem to affect *too* much, and will likely be fixed in the next major release.

**Comment by zxsdklfhskyrvk** [comment] 2019-11-09 23:05
To be clear, you are talking about the game crash I am seeing?  Not just the error message point?

FYI - I looked into a beat saber log indicating the crash and was lead to this Unity issue.

https://forum.unity.com/threads/u5-3-error-symgetsymfromaddr64-getlasterror-attempt-to-access-invalid-address.413565/

As for the impact,  this crash is preventing me from accessing VR, until I manually close the crash dialog in Windows.  I'd say that's a breaking bug.  When I have to stop using the entire platform to recover.

**Comment by nike4613** [comment] 2019-11-10 01:45
Yeah, I believe so. You are talking about a crash when exiting the game through normal means, correct?

As for the impact, at least for SteamVR you can pull up the desktop interface in VR to close it. I've also found that it is intermittent, though I think know the cause and have fixed it in the next version branch.

That thread that you sent seems to be from Unity 5, which is quite old even compared to the version that BS uses. I strongly doubt that the error described there has anything to do with it.

**Comment by zxsdklfhskyrvk** [comment] 2019-11-10 13:40
Correct on the crash.  BTW, that forum post has posts on the issue up until May this year, so it is more likely an ongoing unsolved issue.

**Comment by nike4613** [comment] 2019-12-13 02:27
I believe I have fixed it in the 4.0.0 branch with 69c7a889b209f2b07766e210b44e5fb799c8bd86. Could you test with the build for that commit? Current plugins will not load with it though.

**Comment by zxsdklfhskyrvk** [comment] 2019-12-14 15:34
Sorry, I don't know how to get that build?  If it requires compiling it,  I have no skills or the required tools (Visual Studio).  Let me know and I'll happily test.

**Comment by nike4613** [comment] 2019-12-14 16:31
By the commit message should be a little check mark, if you click on that then go to the first job then the artifacts tab, you should be able to download a build.

**Comment by zxsdklfhskyrvk** [comment] 2019-12-14 16:55
got it.  Is the right process to install only the core mods, and then drop these files on top?   I don't see anything in-game indicating mods are installed when I tried that.  Guessing I should see the SongCore loading?  But,  if this behavior is expected,  then when I close the game,  the crash is NOT occurring.

IPA log is attached
[2019.12.14.11.51.38.log](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/files/3964064/2019.12.14.11.51.38.log)

Latest BS log:
[_latest.log](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/files/3964066/_latest.log)

**Comment by nike4613** [comment] 2019-12-14 23:14
That is the expected output. That version has some incompatibilities with current mods, and so existing mods will not load with it.

Since it seems to be working as expected, closing this issue.

**Comment by zxsdklfhskyrvk** [comment] 2020-01-22 17:51
@nike4613 It seems like this issue returned?

**Comment by nike4613** [comment] 2020-01-22 19:12
That is to be expected as the fix is not in the current releases or master. The fix is currently only in the 4.0.0-beta branch, and that this will likely not be merged because it is nontrivial.

**Comment by nike4613** [comment] 2020-01-22 19:13
Reopening until 4.0.0 is merged.

**Comment by nike4613** [comment] 2020-01-28 18:25
4.0.0 is merged, will close when it is fully released.

**Comment by nike4613** [comment] 2020-03-30 23:18
4.0.0 has been released. Closing.

**Closed as completed by nike4613** 2020-03-30 23:18 UTC
Labels: bug
