### ISSUE TITLE
Errors doing a local build

### ISSUE THREAD

**Issue by ragekillen** [nike4613/BeatSaber-IPA-Reloaded#35] opened 2020-02-08 01:32 UTC
references missing BeatSaberCustomUI Assembly-CSharp Mono.Cecil newtonsoft json and probably more which this all leads to 290 errors during compiling

**Comment by nike4613** [comment] 2020-02-08 19:55
Are you trying to build master? Everything enabled in the build of master works.

**Comment by ragekillen** [comment] 2020-02-08 20:42
Yes i am trying to build master. I dont know what I'm missing if it works correctly. My steps are 1.create bsinstalldir.txt with E:/beat saber/path/ inside 2 set x64-net4 
3. create a build with ctrl +shift+b. result 280-290 errors across the whole project references to jtokens , json missing ipa.loader.dll etc etc

I have always been bad at importing huge projects like this if you could please provide a video it would be greatly appreciated. I'm sure it would help me and many others as I can follow step by step setup following text steps is sometimes a bit confusing

**Comment by nike4613** [comment] 2020-02-08 22:00
If you're missing JObject, that sounds like your VS isn't doing a package restore. Also- are you creating `bsinstalldir.txt` in VS? Because that is known to not work. Its content should also be the path to a Beat Saber installation, not a filler path.

**Comment by ragekillen** [comment] 2020-02-08 22:58
No I created bsinstalldir manually through file explorer and I just gave a filler path here the actuall path is correct on the file. 

As for package restore I will check if it is working but if my steps are correct to you that is more then likely my issue

**Comment by ragekillen** [comment] 2020-02-10 01:32
@nike4613 thank you for recommending to check package restore the console stated a fallback folder was missing under C:/microsoft/xamarin. Creating that folder fixed all but 3 issues 
![c548e6c1c991bdbaf3b7d07ed1d113c1](https://user-images.githubusercontent.com/22842900/74115042-da5b6880-4b72-11ea-87e4-888f8c4dcefd.png)

**Comment by nike4613** [comment] 2020-02-10 03:34
Only the third error there is actually blocking anything (the other 2 are caused by it), but that error doesn't make any sense for master. Look at the error location for something unusual.

**Comment by ragekillen** [comment] 2020-02-10 05:04
![c667840aaf719fb8c74503b9aa81f4c3](https://user-images.githubusercontent.com/22842900/74122222-fde0dc00-4b8f-11ea-9473-26eab1b3bd71.png)

I hope you can help with this i cant tell whats wrong here its the exact same as master it has not been touched since extract

**Comment by ragekillen** [comment] 2020-02-11 19:42
@nike4613 I actually fixed the previous error it was a bug in vs itself I saw someone post about the same thing so after update build went smoothly.  now to figure out why I have no mod tab in-game i believe that is part of bsipa-modlist it's stated that plugin metadata does not exist in the type pluginloader

**Comment by nike4613** [comment] 2020-02-11 21:01
Well, ModList hasn't been updated for the past several updates...

If you have no "mods" tab, thats more likely an issue with BSML, and should be resolved in #pc-help in the BSMG Discord.

**Closed as completed by nike4613** 2020-02-11 21:01 UTC
Labels: question

**Comment by ragekillen** [comment] 2020-02-11 21:27
ok that would make sense why mod list is having build issues. i appreciate all your help thank you
