### ISSUE TITLE
Launch game error : System.NullReferenceException

### ISSUE THREAD

**Issue by barnus88** [nike4613/BeatSaber-IPA-Reloaded#67] opened 2021-05-17 19:10 UTC
Hello,

when i start the game after mod installed (IPA), i have en issue. The game crashes instantly. Looking at the logs, I have the following message : 

> [DEBUG @ 20:47:25 | IPA/LibraryLoader] Found file Newtonsoft.Json.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\Newtonsoft.Json.dll
[ERROR @ 20:47:25 | IPA] Error installing harmony patches to intercept Console color properties:
[ERROR @ 20:47:25 | IPA] System.NullReferenceException: Object reference not set to an instance of an object
[ERROR @ 20:47:25 | IPA]   at System.Guid.NewGuid () [0x00029] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR @ 20:47:25 | IPA]   at Mono.Cecil.ModuleDefinition.CreateModule (System.String name, Mono.Cecil.ModuleParameters parameters) [0x0005b] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at HarmonyLib.HarmonySharedState.CreateModule () [0x00018] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at HarmonyLib.HarmonySharedState.GetState () [0x0001f] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at HarmonyLib.HarmonySharedState.GetPatchInfo (System.Reflection.MethodBase method) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at HarmonyLib.PatchProcessor.Patch () [0x0006d] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer) [0x00028] in <28a34da201e449be81fe5efb7481a26c>:0 
[ERROR @ 20:47:25 | IPA]   at IPA.Logging.StdoutInterceptor+ConsoleHarmonyPatches.Patch (HarmonyLib.Harmony harmony) [0x0005d] in <8e98fd56b0d143f6ba8e9ca7b94817e7>:0 
[INFO @ 20:47:25 | _] System.Security.Cryptography.CryptographicException: Couldn't access random source.
[INFO @ 20:47:25 | _]   at System.Security.Cryptography.RNGCryptoServiceProvider.Check () [0x0001c] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at System.Security.Cryptography.RNGCryptoServiceProvider..ctor () [0x00012] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at System.Guid.FastNewGuidArray () [0x00030] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at System.Reflection.Emit.ModuleBuilder..ctor (System.Reflection.Emit.AssemblyBuilder assb, System.String name, System.String fullyqname, System.Boolean emitSymbolInfo, System.Boolean transient) [0x00035] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name, System.String fileName, System.Boolean emitSymbolInfo, System.Boolean transient) [0x0005b] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name, System.String fileName) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[INFO @ 20:47:25 | _]   at IPA.Config.Stores.GeneratedStoreImpl.get_Module () [0x0003a] in <8e98fd56b0d143f6ba8e9ca7b94817e7>:0 
[INFO @ 20:47:25 | _]   at IPA.Config.Stores.GeneratedStoreImpl.CreateAndInitializeConvertersFor (System.Type type, System.Collections.Generic.IEnumerable`1[T] structure) [0x00012] in <8e98fd5

**Comment by Meivyn** [comment] 2021-05-18 17:02
Can you please contact me on Discord: Meivyn#3705. Be sure to be part of BSMG or you won't be able to send me DMs.

**Comment by nike4613** [comment] 2021-05-18 17:05
This is a duplicate of #60.

**Comment by Meivyn** [comment] 2021-05-18 21:03
This should be fixed somehow in the next release, thanks for your time in finding the cause of this issue.

**Closed as completed** 2021-08-11 19:39 UTC
