### ISSUE TITLE
Doorstop Fatal

### ISSUE THREAD

**Issue by Eggathan** [nike4613/BeatSaber-IPA-Reloaded#78] opened 2022-03-03 03:04 UTC
![image](https://user-images.githubusercontent.com/78398639/156488282-a7ef0fa7-e799-4784-8b62-644b2636ed8a.png)
[_latest.log](https://github.com/bsmg/BeatSaber-IPA-Reloaded/files/8174612/_latest.log)

I don't know why this is happening

**Comment by Meivyn** [comment] 2022-03-14 15:45
Duplicate of #71.

**Closed as not planned** 2022-07-21 06:55 UTC
