### ISSUE TITLE
NullReferenceException on startup with a fresh install

### ISSUE THREAD

**Issue by XanderStoffels** [nike4613/BeatSaber-IPA-Reloaded#68] opened 2021-05-18 19:53 UTC
Hi all, got some problems while running a fresh install.

With fresh install I mean I downloaded the game from steam, ran it once, then proceeded to follow the steps shown in [the documentation](https://bsmg.github.io/BeatSaber-IPA-Reloaded/articles/start-user.html).

Version: BSIPA 4.1.6
Error log: [_latest.log](https://github.com/bsmg/BeatSaber-IPA-Reloaded/files/6503894/_latest.log)

Did some digging around, found out the exception is occurring [here](https://github.com/bsmg/BeatSaber-IPA-Reloaded/blob/master/IPA.Loader/Logging/StdoutInterceptor.cs#L137). 
Commit https://github.com/bsmg/BeatSaber-IPA-Reloaded/commit/078ff43f92183161caeebcf98d73b856aa2e21ee seems to address some related issue here, but I have no idea how to fix that.

Any help would be appreciated.

**Comment by Meivyn** [comment] 2021-05-27 20:22
Duplicate of #60 and #67. 

We have made progress on this issue and we found out that this was caused by something in the `Path`. Can you please run this command and show us its output?

On PowerShell:

```powershell
$Env:Path
```

On CMD:

```cmd
echo %Path%
```

We will compare your `Path` with that of another user and see what matches. This should help speed up the process.

**Comment by XanderStoffels** [comment] 2021-05-27 20:57
[path.txt](https://github.com/bsmg/BeatSaber-IPA-Reloaded/files/6556779/path.txt)

Thanks for investigating.

**Comment by Meivyn** [comment] 2021-05-27 21:14
Please contact me on Discord if you're willing to help: Meivyn#3705.

**Comment by Meivyn** [comment] 2021-05-28 06:53
If you are willing to help, contact me on Discord: Meivyn#3705

**Comment by Meivyn** [comment] 2021-05-28 19:25
Thanks for your help @barnus88 and @XanderStoffels on finding the issue, now we know exactly *what* is the problem, we don't know yet *why* but it may be a Windows bug.

For reference, the issue happens when there is a `.exe` file directly in the `Path`, it may also be triggered with any non-directory paths. As a temporary fix, remove those from your `Path`, they shouldn't be there anyway and won't work.

@nike4613 will take care of that from now on.

**Comment by nike4613** [comment] 2021-05-28 19:52
More specifically, it seems to only care if it is an OS reparse point with LinkType (as reported by PowerShell) `AppExeCLink`, like what Store apps generate in `~\AppData\Local\Microsoft\WindowsApps` so they can be run from the command line.

**Comment by Meivyn** [comment] 2021-09-06 18:29
Found out with another user report that `~\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\bin` is also causing this issue.

Problematic entries we have found with users since this issue was reported:

1. #60 Unknown
2. #61 Unknown
3. #67 `~\AppData\Local\Microsoft\WindowsApps\python.exe`
4. #68 `~\AppData\Local\Microsoft\WindowsApps\wt.exe`
5. Reported in DM `~\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\bin` (also a file)

**Closed as completed** 2021-12-15 23:18 UTC
